### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by kevinch3-shoutly** [drobinetm/drm-ng-countries-flags#4]
I'm stucked on this error

![Screenshot 2021-09-24 at 14 13 32](https://user-images.githubusercontent.com/45036489/134672301-79385365-f840-4cfd-b6c3-9a01aa992936.png)

deps are installed    
`
"flag-icon-css": "^3.3.0",
"country-list": "^2.1.1",
`

**Comment by drobinetm** [comment]
mmm, you upgrade your angular project?

**Comment by drobinetm** [comment]
> I'm stucked on this error
> 
> ![Screenshot 2021-09-24 at 14 13 32](https://user-images.githubusercontent.com/45036489/134672301-79385365-f840-4cfd-b6c3-9a01aa992936.png)
> 
> deps are installed
> `"flag-icon-css": "^3.3.0", "country-list": "^2.1.1",`

ok, I fixed the problem by removing the pair dependencies from package.json. I uploaded a new version of the project
